### ISSUE TITLE
Placeholder for adding contributors for 04/04/20

### ISSUE THREAD

**Issue by clarkio** [clarkio/streaming-guide#19]
Do the thang!

**Comment by opti21** [comment]
I'm opti_21 from twitch 🎉

**Comment by archification** [comment]
Hello there. archification from twitch

**Comment by lemueldls** [comment]
Looks great

**Comment by clarkio** [comment]
@all-contributors please add @opti21 for docs and ideas

**Comment by clarkio** [comment]
@all-contributors please add @codephobia for docs and ideas

**Comment by clarkio** [comment]
@all-contributors please add @archification for docs and ideas

**Comment by clarkio** [comment]
@all-contributors please add @lemueldls for docs and ideas

**Comment by clarkio** [comment]
@all-contributors please add @matthewkosloski for docs and ideas

**Comment by clarkio** [comment]
@all-contributors please add @therealpygon for docs and ideas

**Comment by clarkio** [comment]
@all-contributors please add @AlliDoisCode1234 for docs and ideas

**Comment by clarkio** [comment]
Thanks again everyone for helping out during the stream today!
